Поэкспериментируйте с функцией iinfo и узнайте границы типов данных int16, int32 и int64

In [10]:
import numpy as np
print (np.uint8(-456))


56


C:\Users\Mironkin\AppData\Local\Temp\ipykernel_19940\893418986.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  print (np.uint8(-456))


np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [14]:
import numpy as np
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print (step)

0.45


Выполните все пукты задания по порядку.
Пожалуйста, не меняйте названия переменных, в которых должны появиться ответы.

В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца
В переменную last сохраните элемент из последней строки последнего столбца
В переменную line_4 сохраните строку 4
В переменную col_2 сохраните предпоследний столбец
Из строк 2-4 (включительно) получите столбцы 3-5 (включительно). Результат сохраните в переменную part
Сохраните в переменную rev последний столбец в обратном порядке
Сохраните в переменную trans транспонированный массив

In [29]:
import numpy as np
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],                    
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
elem_5_3 = mystery[5,3]
last = mystery [-1,-1]
line_4 = mystery[4]
col_2 = mystery[::,-2:-1]
part  = mystery [2:5,3:6]
rev = mystery[:,-1][::-1]
print (rev)

[-32037  29943   -564   8225   7181 -18049]


Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено
В переменную n_nan сохраните число пропущенных значений
Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями
Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int
Отсортируйте значения в массиве mystery по возрастанию и сохраните результат в переменную array
Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!

In [43]:
import numpy as np
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery)
n_nan=np.isnan(mystery).sum()
mystery_new=mystery.copy()
mystery_new[np.isnan(mystery_new)]=0
mystery_int = np.int32(mystery)
array =np.sort(mystery)
table = mystery.reshape(5,3,order='F')
print (table)


[[ 12279.  -2365.  16132.]
 [-26024.  -6974.  25933.]
 [ 28745.  -9212.     nan]
 [    nan     nan -16431.]
 [ 31244. -17722.  29810.]]


C:\Users\Mironkin\AppData\Local\Temp\ipykernel_19940\1382237778.py:9: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)


In [15]:
import numpy as np
def min_max_dist(*vectors):
    res_min=2**32
    res_max=0
    for vec1 in vectors:
        for vec2 in vectors:
            if np.linalg.norm(vec1-vec2)!=0:
                res_min = np.min([res_min,np.linalg.norm(vec1-vec2)])
                res_max = np.max([res_max,np.linalg.norm(vec1-vec2)])

    return (res_min,res_max)
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

In [29]:
import numpy as np
def get_unique_loto(num):
    res=np.zeros((num,5,5))
    i=0
    while i!=num: 
        res[i]=np.random.choice(101,size=(5,5),replace=False)
        i+=1
    return res
print (get_unique_loto(3))

[[[13. 87.  4. 37. 34.]
  [41. 21. 70. 80. 52.]
  [33.  0.  2. 69. 59.]
  [97. 35. 60. 62. 72.]
  [68. 91.  3. 74. 63.]]

 [[98.  6. 66. 57. 13.]
  [24. 73. 65. 26. 15.]
  [25. 47. 99. 45. 92.]
  [76. 87. 43. 80. 29.]
  [17. 55. 74. 94. 38.]]

 [[32. 68. 67. 21. 93.]
  [99. 20. 17. 46. 66.]
  [45.  4. 51. 54. 60.]
  [ 9. 31. 78. 85. 26.]
  [50. 82. 52. 43. 62.]]]
